### ISSUE TITLE
fix: crashes after patching iOS since Shorebird 0.20.0

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1623]
We've had now 3 reports of users experiencing crashes when patching iOS since 0.20.0 (which contained our new iOS engine).

0.20.0 (and 0.21.0 and 0.21.1) pass all of our (10k+) tests and our test apps, but I'm totally willing to believe there are crashes we've not yet found.  We've fixed additional crashes in the new iOS engine since that time, but believed at the time those crashes were not on code-paths we had enabled in 0.20.0.

If anyone has a crash stack they could share (either by posting on this bug or emailing contact@shorebird.dev) that would be very helpful.  Thank you.

Our choices are:
1.  Fix a crash once we have a crash stack and/or reproduction from a user.
2. Just wait and release our updated engine later this week / early next (which has a bunch of fixes, possibly including fixing crashers users might have seen).
3. Roll back the latest Shorebird to an iOS alpha which is 0.19.x or earlier.

At this time we're currently tending towards 2.   With more information we're happy to explore 1 or 2.

I would encourage all customers to use `shorebird preview` to test patches locally before deploying to the wild.  We try hard to make sure we never crash your app, but it's always possible we've missed something in testing.  Thanks!

**Comment by eseidel** [comment]
Got one crash report from a customer just now:
```
Crashed: io.flutter.1.ui
0  ???                            0x156758014 (Missing)
1  App                            0x1f148 stub _iso_stub_InitAsyncStub + 65224
2  Flutter                        0x18134 EndTransitionDartToCpuIfNeeded + 284
3  ???                            0x10a104e5c (Missing)
4  ???                            0x10a104da4 (Missing)
5  ???                            0x10a104d18 (Missing)
6  ???                            0x10a063aa8 (Missing)
7  ???                            0x10a7ee97c (Missing)
8  ???                            0x109e9ad18 (Missing)
9  ???                            0x109e9aba8 (Missing)
10 ???                            0x109e98ec4 (Missing)
11 ???                            0x109e98ae8 (Missing)
12 ???                            0x109e98a5c (Missing)
13 ???                            0x109e98890 (Missing)
14 ???                            0x109e98780 (Missing)
15 ???                            0x109e98744 (Missing)
16 App                            0xc298 stub InvokeDartCode + 33432
17 ???                            0xffffffffe (Missing)
```

I don't have the crash point (to know if this is a null pointer, etc.).

But it looks like: `0x1f148 stub _iso_stub_InitAsyncStub + 65224` says it's 65224 bytes after the start of _iso_stub_InitAsyncStub which means it's not actually in `_iso_stub_InitAsyncStub`, but rather just that Crashlytics (where we were given this report from) did not have the necessary symbols to identify that.

However the fact hat it attributes it to "App" might suggest that it was still within the loaded region for the "base" snapshot and thus running CPU code (rather than simulator), which is further supported by the crash stack which suggests the frame above is EndTransitionDartToCpuIfNeeded + 284 (meaning 71 instructions past the start of _RunDartOnCPU) which seems very plausible.

I think that's probably as much as we can get out of this stack, short of getting the exact flutter revision this was built from (which we could get from the app_id from the customer) and then potentially doing our own symbolication, although I'm sure it would yield better than what Crashlytics did, although possibly since the customer likely did not upload a fully symbolicated Flutter engine to crashlytics which we could relatively easily obtain from download.shorebird.dev.

**Comment by eseidel** [comment]
My recommendation to any customer who is concerned about this would be to wait another couple days until we release another ios-alpha.  It would be possible to downgrade to 0.19.0 Shorebird and release with that if needed as well.

**Comment by sharhan108** [comment]
We had the same issue, instead of downgrading shorebird, shall we downgrade the version of flutter like this: https://docs.shorebird.dev/flutter-version 
 
<img width="439" alt="Screenshot 2024-01-10 at 1 32 54 PM" src="https://github.com/shorebirdtech/shorebird/assets/134387336/5b80ade6-dd3a-4bf3-9e48-b830d1a80348">

**Comment by eseidel** [comment]
@sharhan108's suggestion is correct.  Using Flutter 3.16.4 or earlier is probably the easiest way to avoid the crash if anyone is experiencing it:
```
shorebird flutter versions use 3.16.4
```

Note that that will only change the flutter version used for *releasing* since the flutter version used for *patching* is automatically set by Shorebird to match whatever you used when releasing.

**Comment by eseidel** [comment]
We believe all known crashers are resolved in 0.22.0.  We also fixed `shorebird` to work with older Flutter versions again, so you should be able to try either a newer flutter or older Flutter and have the crashes fixed.  Please let us know if you see any issues.

https://github.com/shorebirdtech/shorebird/releases

We recommend testing patches with `shorebird preview` before deploying to users.

**Comment by susantimilsina** [comment]
@eseidel I experienced crashes in the latest version as well. Initially, I doubted my step-by-step process, which is why I suggested creating a video featuring apps from both the Play Store and the App Store(If you remember i had left a comment on youtube channel). This was to verify if I was following the correct steps. However, considering the crashes reported by users, it seems the issue persists in the newer version too. I am using this versions.
Shorebird 0.23.0 • [git@github.com](mailto:git@github.com):shorebirdtech/shorebird.git
Flutter 3.16.7 • revision dea76906e4e34285a1910563efac89f4766cd649
Engine • revision d50060c4046447ce7edf24008d24b1be7fd953f0

**Comment by eseidel** [comment]
> @eseidel I experienced crashes in the latest version as well. Initially, I doubted my step-by-step process, which is why I suggested creating a video featuring apps from both the Play Store and the App Store(If you remember i had left a comment on youtube channel). This was to verify if I was following the correct steps. However, considering the crashes reported by users, it seems the issue persists in the newer version too. I am using this versions. Shorebird 0.23.0 • [git@github.com](mailto:git@github.com):shorebirdtech/shorebird.git Flutter 3.16.7 • revision dea76906e4e34285a1910563efac89f4766cd649 Engine • revision d50060c4046447ce7edf24008d24b1be7fd953f0

Thank you for the report!  We would love to help diagnose and fix the crashes.  Are you able to file an issue with a crash report?  We're also reachable on https://discord.gg/shorebird as well as contact@shorebird.dev if needed.  Thank you.

**Comment by moweiran** [comment]
We are still crash in the latest version v0.23.1

```
lzy@LZYdeMac-mini astrostar-app % shorebird doctor   
Shorebird 0.23.1 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.16.4 • revision 7e92b034c5dddb727cf5e802c23cddd39b325a7f
Engine • revision 9472e50354253fde3f2cdb25d8115f7aa6d3c68a

✓ Shorebird is up-to-date (1.1s)
✓ Flutter install is correct (0.6s)
✓ AndroidManifest.xml files contain INTERNET permission (35ms)
✓ Has access to storage.googleapis.com (1.0s)

No issues detected!
lzy@LZYdeMac-mini astrostar-app % shorebird flutter versions list
📦 Flutter Versions
  3.16.7
  3.16.5
✓ 3.16.4
  3.16.3
  3.13.9
```

the crash log 
```
# Crashlytics - Stack trace
# Application: live.astrostar.dev
# Platform: apple
# Version: 2.10.0 (78)
# Issue: 289a3c868840634daf068a36cb5111f9
# Session: e649671c66c3495a81b01b9a3fe57b0e_DNE_0_v2
# Date: Mon Jan 29 2024 14:41:00 GMT+0800 (中国标准时间)

com.apple.main-thread
0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
4  CoreFoundation                 0x79024 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7a250 __CFRunLoopRun + 1208
6  CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
7  GraphicsServices               0x135c GSEventRunModal + 164
8  UIKitCore                      0x39cf58 -[UIApplication _run] + 888
9  UIKitCore                      0x39cbbc UIApplicationMain + 340
10 AstroStar Dev                  0x8e40 main + 7 (AppDelegate.swift:7)
11 ???                            0x1dc564dec (Missing)

Thread
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  libc++.1.dylib                 0x12f8c std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 100
3  AgoraRtcWrapper                0x201c8 std::__1::cv_status std::__1::condition_variable::wait_for<long long, std::__1::ratio<1l, 1000000000l>>(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>> const&) + 192
4  AgoraRtcWrapper                0x200f0 void std::__1::condition_variable::__do_timed_wait<std::__1::chrono::steady_clock>(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>>) + 60
5  AgoraRtcWrapper                0x2008c std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>>(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>> const&) + 56
6  AgoraRtcWrapper                0x20028 bool std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>, spdlog::details::periodic_worker::periodic_worker(std::__1::function<void ()> const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l>>)::'lambda'()::operator()() const::'lambda'()>(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>> const&, spdlog::details::periodic_worker::periodic_worker(std::__1::function<void ()> const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l>>)::'lambda'()::operator()() const::'lambda'()) + 56
7  AgoraRtcWrapper                0x1ff50 spdlog::details::periodic_worker::periodic_worker(std::__1::function<void ()> const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l>>)::'lambda'()::operator()() const + 112
8  AgoraRtcWrapper                0x1fe24 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, spdlog::details::periodic_worker::periodic_worker(std::__1::function<void ()> const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l>>)::'lambda'()>>(void*) + 48
9  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
10 libsystem_pthread.dylib        0xb88 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread· + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
4  CoreFoundation                 0x79024 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7a250 __CFRunLoopRun + 1208
6  CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
7  Foundation                     0x41fb4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0x41e9c -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9  UIKitCore                      0x4cfcc8 -[UIEventFetcher threadMain] + 416
10 Foundation                     0x5b524 __NSThread__start__ + 716
11 libsystem_pthread.dylib        0x16b8 _pthread_start + 148
12 libsystem_pthread.dylib        0xb88 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

Thread
0  libsystem_pthread.dylib        0xb74 start_wqthread + 254

Crashed: io.flutter.1.ui
0  ???                            0x139a60014 (Missing)
1  App                            0x634134 kDartIsolateSnapshotInstructions + 6442676
2  Flutter                        0x18134 EndTransitionDartToCpuIfNeeded + 284
3  ???                            0x112b851b4 (Missing)
4  ???                            0x112b86118 (Missing)
5  ???                            0x112b86008 (Missing)
6  ???                            0x112b8645c (Missing)
7  ???                            0x112b8645c (Missing)
8  ???                            0x112b8645c (Missing)
9  ???                            0x112b8645c (Missing)
10 ???                            0x112b8a188 (Missing)
11 ???                            0x112b8a404 (Missing)
12 ???                            0x112b882d4 (Missing)
13 ???                            0x112b8645c (Missing)
14 ???                            0x112b8a188 (Missing)
15 ???                            0x112b880e0 (Missing)
16 ???                            0x112b8645c (Missing)
17 ???                            0x112b8a188 (Missing)
18 ???                            0x112b880e0 (Missing)
19 ???                            0x112b8a188 (Missing)
20 ???                            0x112b8a404 (Missing)
21 ???                            0x112b882d4 (Missing)
22 ???                            0x112b8a188 (Missing)
23 ???                            0x112b8818c (Missing)
24 ???                            0x112b8a188 (Missing)
25 ???                            0x112b8818c (Missing)
26 ???                            0x112b8a188 (Missing)
27 ???                            0x112b880e0 (Missing)
28 ???                            0x112b8a188 (Missing)
29 ???                            0x112b8a404 (Missing)
30 ???                            0x112b882d4 (Missing)
31 ???                            0x112b8a188 (Missing)
32 ???                            0x112b8a404 (Missing)
33 ???                            0x112b882d4 (Missing)
34 ???                            0x112b85d24 (Missing)
35 ???                            0x112b86118 (Missing)
36 ???                            0x112b8645c (Missing)
37 ???                            0x112b8a188 (Missing)
38 ???                            0x112b8818c (Missing)
39 ???                            0x112b8a188 (Missing)
40 ???                            0x112b8a404 (Missing)
41 ???                            0x11267dcc8 (Missing)
42 ???                            0x11266ab2c (Missing)
43 ???                            0x11266a4e8 (Missing)
44 ???                            0x11266a4b0 (Missing)
45 ???                            0x1125d97c4 (Missing)
46 ???                            0x1125d96f4 (Missing)
47 ???                            0x1125d93fc (Missing)
48 ???                            0x1125d92d0 (Missing)
49 ???                            0x112544e90 (Missing)
50 ???                            0x112544f84 (Missing)
51 ???                            0x112d98c1c (Missing)
52 ???                            0x112d99598 (Missing)
53 ???                            0x11257a324 (Missing)
54 ???                            0x11257e754 (Missing)
55 ???                            0x11257e6ec (Missing)
56 ???                            0x11257e78c (Missing)
57 App                            0xc298 kDartVmSnapshotInstructions + 33432
58 ???                            0xffffffffe (Missing)

io.flutter.1.raster
0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
4  CoreFoundation                 0x79024 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7a250 __CFRunLoopRun + 1208
6  CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
7  Flutter                        0x6ef1b8 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2994776
8  Flutter                        0x6ee82c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2992332
9  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
10 libsystem_pthread.dylib        0xb88 thread_start + 8

io.flutter.1.io
0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
4  CoreFoundation                 0x79024 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7a250 __CFRunLoopRun + 1208
6  CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
7  Flutter                        0x6ef1b8 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2994776
8  Flutter                        0x6ee82c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2992332
9  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
10 libsystem_pthread.dylib        0xb88 thread_start + 8

io.worker.1
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  Flutter                        0x45cd18 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 298424
3  Flutter                        0x6e840c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2966700
4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
5  libsystem_pthread.dylib        0xb88 thread_start + 8

io.worker.2
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  Flutter                        0x45cd18 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 298424
3  Flutter                        0x6e840c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2966700
4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
5  libsystem_pthread.dylib        0xb88 thread_start + 8

io.worker.3
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  Flutter                        0x45cd18 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 298424
3  Flutter                        0x6e840c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2966700
4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
5  libsystem_pthread.dylib        0xb88 thread_start + 8

io.worker.4
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  Flutter                        0x45cd18 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 298424
3  Flutter                        0x6e840c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2966700
4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
5  libsystem_pthread.dylib        0xb88 thread_start + 8

io.worker.5
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  Flutter                        0x45cd18 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 298424
3  Flutter                        0x6e840c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2966700
4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
5  libsystem_pthread.dylib        0xb88 thread_start + 8

io.worker.6
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  Flutter                        0x45cd18 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 298424
3  Flutter                        0x6e840c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2966700
4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
5  libsystem_pthread.dylib        0xb88 thread_start + 8

dart:io EventHandler
0  libsystem_kernel.dylib         0x25dc kevent + 8
1  Flutter                        0x9a7628 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 5846728
2  Flutter                        0x9d511c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 6033852
3  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
4  libsystem_pthread.dylib        0xb88 thread_start + 8

io.worker.1
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  Flutter                        0x45cd18 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 298424
3  Flutter                        0x6e840c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2966700
4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
5  libsystem_pthread.dylib        0xb88 thread_start + 8

io.worker.2
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  Flutter                        0x45cd18 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 298424
3  Flutter                        0x6e840c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2966700
4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
5  libsystem_pthread.dylib        0xb88 thread_start + 8

io.worker.3
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  Flutter                        0x45cd18 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 298424
3  Flutter                        0x6e840c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2966700
4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
5  libsystem_pthread.dylib        0xb88 thread_start + 8

io.worker.4
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  Flutter                        0x45cd18 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 298424
3  Flutter                        0x6e840c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2966700
4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
5  libsystem_pthread.dylib        0xb88 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb7c start_wqthread + 8

com.google.firebase.crashlytics.MachExceptionServer
0  FirebaseCrashlytics            0x21794 FIRCLSProcessRecordAllThreads + 184
1  FirebaseCrashlytics            0x21b74 FIRCLSProcessRecordAllThreads + 1176
2  FirebaseCrashlytics            0x18c24 FIRCLSHandler + 48
3  FirebaseCrashlytics            0x1b4a8 FIRCLSMachExceptionServer + 688
4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
5  libsystem_pthread.dylib        0xb88 thread_start + 8

JavaScriptCore libpas scavenger
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  JavaScriptCore                 0x113d84 scavenger_thread_main + 1620
3  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
4  libsystem_pthread.dylib        0xb88 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x80a4 _pthread_cond_wait + 1276
2  Flutter                        0xa9e6c8 InternalFlutterGpuTestClass_Method + 755488
3  Flutter                        0xae565c InternalFlutterGpuTestClass_Method + 1046196
4  Flutter                        0xa9e094 InternalFlutterGpuTestClass_Method + 753900
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x80a4 _pthread_cond_wait + 1276
2  Flutter                        0xa9e6c8 InternalFlutterGpuTestClass_Method + 755488
3  Flutter                        0xae565c InternalFlutterGpuTestClass_Method + 1046196
4  Flutter                        0xa9e094 InternalFlutterGpuTestClass_Method + 753900
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x80a4 _pthread_cond_wait + 1276
2  Flutter                        0xa9e6c8 InternalFlutterGpuTestClass_Method + 755488
3  Flutter                        0xa35990 InternalFlutterGpuTestClass_Method + 326120
4  Flutter                        0xae5690 InternalFlutterGpuTestClass_Method + 1046248
5  Flutter                        0xa9e094 InternalFlutterGpuTestClass_Method + 753900
6  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
7  libsystem_pthread.dylib        0xb88 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x80a4 _pthread_cond_wait + 1276
2  Flutter                        0xa9e6c8 InternalFlutterGpuTestClass_Method + 755488
3  Flutter                        0xae565c InternalFlutterGpuTestClass_Method + 1046196
4  Flutter                        0xa9e094 InternalFlutterGpuTestClass_Method + 753900
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
4  CoreFoundation                 0x79024 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7a250 __CFRunLoopRun + 1208
6  CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
7  CFNetwork                      0x2586f0 _CFURLStorageSessionDisableCache + 60900
8  Foundation                     0x5b524 __NSThread__start__ + 716
9  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
10 libsystem_pthread.dylib        0xb88 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x80a4 _pthread_cond_wait + 1276
2  Flutter                        0xa9e6c8 InternalFlutterGpuTestClass_Method + 755488
3  Flutter                        0xae565c InternalFlutterGpuTestClass_Method + 1046196
4  Flutter                        0xa9e094 InternalFlutterGpuTestClass_Method + 753900
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x80a4 _pthread_cond_wait + 1276
2  Flutter                        0xa9e6c8 InternalFlutterGpuTestClass_Method + 755488
3  Flutter                        0xae565c InternalFlutterGpuTestClass_Method + 1046196
4  Flutter                        0xa9e094 InternalFlutterGpuTestClass_Method + 753900
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x80a4 _pthread_cond_wait + 1276
2  Flutter                        0xa9e6c8 InternalFlutterGpuTestClass_Method + 755488
3  Flutter                        0xae565c InternalFlutterGpuTestClass_Method + 1046196
4  Flutter                        0xa9e094 InternalFlutterGpuTestClass_Method + 753900
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x80a4 _pthread_cond_wait + 1276
2  Flutter                        0xa9e6c8 InternalFlutterGpuTestClass_Method + 755488
3  Flutter                        0xae565c InternalFlutterGpuTestClass_Method + 1046196
4  Flutter                        0xa9e094 InternalFlutterGpuTestClass_Method + 753900
5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
6  libsystem_pthread.dylib        0xb88 thread_start + 8

com.apple.coremedia.rootQueue.47
0  libsystem_kernel.dylib         0xc38 semaphore_timedwait_trap + 8
1  libdispatch.dylib              0x44c4 _dispatch_sema4_timedwait + 64
2  libdispatch.dylib              0x4ac4 _dispatch_semaphore_wait_slow + 76
3  libdispatch.dylib              0x15718 _dispatch_worker_thread + 324
4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
5  libsystem_pthread.dylib        0xb88 thread_start + 8

com.apple.coremedia.rootQueue.47
0  libsystem_kernel.dylib         0xc38 semaphore_timedwait_trap + 8
1  libdispatch.dylib              0x44c4 _dispatch_sema4_timedwait + 64
2  libdispatch.dylib              0x4ac4 _dispatch_semaphore_wait_slow + 76
3  libdispatch.dylib              0x15718 _dispatch_worker_thread + 324
4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
5  libsystem_pthread.dylib        0xb88 thread_start + 8

com.apple.coremedia.rootQueue.47
0  libsystem_kernel.dylib         0xc38 semaphore_timedwait_trap + 8
1  libdispatch.dylib              0x44c4 _dispatch_sema4_timedwait + 64
2  libdispatch.dylib              0x4ac4 _dispatch_semaphore_wait_slow + 76
3  libdispatch.dylib              0x15718 _dispatch_worker_thread + 324
4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
5  libsystem_pthread.dylib        0xb88 thread_start + 8
```

**Comment by eseidel** [comment]
> We are still crash in the latest version v0.23.1
> 
> ```
> lzy@LZYdeMac-mini astrostar-app % shorebird doctor   
> Shorebird 0.23.1 • git@github.com:shorebirdtech/shorebird.git
> Flutter 3.16.4 • revision 7e92b034c5dddb727cf5e802c23cddd39b325a7f
> Engine • revision 9472e50354253fde3f2cdb25d8115f7aa6d3c68a
> 
> ✓ Shorebird is up-to-date (1.1s)
> ✓ Flutter install is correct (0.6s)
> ✓ AndroidManifest.xml files contain INTERNET permission (35ms)
> ✓ Has access to storage.googleapis.com (1.0s)
> 
> No issues detected!
> lzy@LZYdeMac-mini astrostar-app % shorebird flutter versions list
> 📦 Flutter Versions
>   3.16.7
>   3.16.5
> ✓ 3.16.4
>   3.16.3
>   3.13.9
> ```
> 
> the crash log
> 
> ```
> # Crashlytics - Stack trace
> # Application: live.astrostar.dev
> # Platform: apple
> # Version: 2.10.0 (78)
> # Issue: 289a3c868840634daf068a36cb5111f9
> # Session: e649671c66c3495a81b01b9a3fe57b0e_DNE_0_v2
> # Date: Mon Jan 29 2024 14:41:00 GMT+0800 (中国标准时间)
> 
> com.apple.main-thread
> 0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
> 1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
> 2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
> 3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
> 4  CoreFoundation                 0x79024 __CFRunLoopServiceMachPort + 160
> 5  CoreFoundation                 0x7a250 __CFRunLoopRun + 1208
> 6  CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
> 7  GraphicsServices               0x135c GSEventRunModal + 164
> 8  UIKitCore                      0x39cf58 -[UIApplication _run] + 888
> 9  UIKitCore                      0x39cbbc UIApplicationMain + 340
> 10 AstroStar Dev                  0x8e40 main + 7 (AppDelegate.swift:7)
> 11 ???                            0x1dc564dec (Missing)
> 
> Thread
> 0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
> 2  libc++.1.dylib                 0x12f8c std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 100
> 3  AgoraRtcWrapper                0x201c8 std::__1::cv_status std::__1::condition_variable::wait_for<long long, std::__1::ratio<1l, 1000000000l>>(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>> const&) + 192
> 4  AgoraRtcWrapper                0x200f0 void std::__1::condition_variable::__do_timed_wait<std::__1::chrono::steady_clock>(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>>) + 60
> 5  AgoraRtcWrapper                0x2008c std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>>(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>> const&) + 56
> 6  AgoraRtcWrapper                0x20028 bool std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>, spdlog::details::periodic_worker::periodic_worker(std::__1::function<void ()> const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l>>)::'lambda'()::operator()() const::'lambda'()>(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>> const&, spdlog::details::periodic_worker::periodic_worker(std::__1::function<void ()> const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l>>)::'lambda'()::operator()() const::'lambda'()) + 56
> 7  AgoraRtcWrapper                0x1ff50 spdlog::details::periodic_worker::periodic_worker(std::__1::function<void ()> const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l>>)::'lambda'()::operator()() const + 112
> 8  AgoraRtcWrapper                0x1fe24 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, spdlog::details::periodic_worker::periodic_worker(std::__1::function<void ()> const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l>>)::'lambda'()>>(void*) + 48
> 9  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 10 libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> Thread
> 0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
> 2  libsystem_pthread.dylib        0xb7c start_wqthread + 8
> 
> Thread
> 0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0xe28 _pthread_wqthread· + 364
> 2  libsystem_pthread.dylib        0xb7c start_wqthread + 8
> 
> Thread
> 0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
> 2  libsystem_pthread.dylib        0xb7c start_wqthread + 8
> 
> com.apple.uikit.eventfetch-thread
> 0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
> 1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
> 2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
> 3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
> 4  CoreFoundation                 0x79024 __CFRunLoopServiceMachPort + 160
> 5  CoreFoundation                 0x7a250 __CFRunLoopRun + 1208
> 6  CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
> 7  Foundation                     0x41fb4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
> 8  Foundation                     0x41e9c -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
> 9  UIKitCore                      0x4cfcc8 -[UIEventFetcher threadMain] + 416
> 10 Foundation                     0x5b524 __NSThread__start__ + 716
> 11 libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 12 libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> Thread
> 0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
> 2  libsystem_pthread.dylib        0xb7c start_wqthread + 8
> 
> Thread
> 0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
> 2  libsystem_pthread.dylib        0xb7c start_wqthread + 8
> 
> Thread
> 0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
> 2  libsystem_pthread.dylib        0xb7c start_wqthread + 8
> 
> Thread
> 0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
> 2  libsystem_pthread.dylib        0xb7c start_wqthread + 8
> 
> Thread
> 0  libsystem_pthread.dylib        0xb74 start_wqthread + 254
> 
> Crashed: io.flutter.1.ui
> 0  ???                            0x139a60014 (Missing)
> 1  App                            0x634134 kDartIsolateSnapshotInstructions + 6442676
> 2  Flutter                        0x18134 EndTransitionDartToCpuIfNeeded + 284
> 3  ???                            0x112b851b4 (Missing)
> 4  ???                            0x112b86118 (Missing)
> 5  ???                            0x112b86008 (Missing)
> 6  ???                            0x112b8645c (Missing)
> 7  ???                            0x112b8645c (Missing)
> 8  ???                            0x112b8645c (Missing)
> 9  ???                            0x112b8645c (Missing)
> 10 ???                            0x112b8a188 (Missing)
> 11 ???                            0x112b8a404 (Missing)
> 12 ???                            0x112b882d4 (Missing)
> 13 ???                            0x112b8645c (Missing)
> 14 ???                            0x112b8a188 (Missing)
> 15 ???                            0x112b880e0 (Missing)
> 16 ???                            0x112b8645c (Missing)
> 17 ???                            0x112b8a188 (Missing)
> 18 ???                            0x112b880e0 (Missing)
> 19 ???                            0x112b8a188 (Missing)
> 20 ???                            0x112b8a404 (Missing)
> 21 ???                            0x112b882d4 (Missing)
> 22 ???                            0x112b8a188 (Missing)
> 23 ???                            0x112b8818c (Missing)
> 24 ???                            0x112b8a188 (Missing)
> 25 ???                            0x112b8818c (Missing)
> 26 ???                            0x112b8a188 (Missing)
> 27 ???                            0x112b880e0 (Missing)
> 28 ???                            0x112b8a188 (Missing)
> 29 ???                            0x112b8a404 (Missing)
> 30 ???                            0x112b882d4 (Missing)
> 31 ???                            0x112b8a188 (Missing)
> 32 ???                            0x112b8a404 (Missing)
> 33 ???                            0x112b882d4 (Missing)
> 34 ???                            0x112b85d24 (Missing)
> 35 ???                            0x112b86118 (Missing)
> 36 ???                            0x112b8645c (Missing)
> 37 ???                            0x112b8a188 (Missing)
> 38 ???                            0x112b8818c (Missing)
> 39 ???                            0x112b8a188 (Missing)
> 40 ???                            0x112b8a404 (Missing)
> 41 ???                            0x11267dcc8 (Missing)
> 42 ???                            0x11266ab2c (Missing)
> 43 ???                            0x11266a4e8 (Missing)
> 44 ???                            0x11266a4b0 (Missing)
> 45 ???                            0x1125d97c4 (Missing)
> 46 ???                            0x1125d96f4 (Missing)
> 47 ???                            0x1125d93fc (Missing)
> 48 ???                            0x1125d92d0 (Missing)
> 49 ???                            0x112544e90 (Missing)
> 50 ???                            0x112544f84 (Missing)
> 51 ???                            0x112d98c1c (Missing)
> 52 ???                            0x112d99598 (Missing)
> 53 ???                            0x11257a324 (Missing)
> 54 ???                            0x11257e754 (Missing)
> 55 ???                            0x11257e6ec (Missing)
> 56 ???                            0x11257e78c (Missing)
> 57 App                            0xc298 kDartVmSnapshotInstructions + 33432
> 58 ???                            0xffffffffe (Missing)
> 
> io.flutter.1.raster
> 0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
> 1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
> 2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
> 3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
> 4  CoreFoundation                 0x79024 __CFRunLoopServiceMachPort + 160
> 5  CoreFoundation                 0x7a250 __CFRunLoopRun + 1208
> 6  CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
> 7  Flutter                        0x6ef1b8 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2994776
> 8  Flutter                        0x6ee82c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2992332
> 9  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 10 libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> io.flutter.1.io
> 0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
> 1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
> 2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
> 3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
> 4  CoreFoundation                 0x79024 __CFRunLoopServiceMachPort + 160
> 5  CoreFoundation                 0x7a250 __CFRunLoopRun + 1208
> 6  CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
> 7  Flutter                        0x6ef1b8 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2994776
> 8  Flutter                        0x6ee82c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2992332
> 9  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 10 libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> io.worker.1
> 0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
> 2  Flutter                        0x45cd18 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 298424
> 3  Flutter                        0x6e840c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2966700
> 4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 5  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> io.worker.2
> 0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
> 2  Flutter                        0x45cd18 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 298424
> 3  Flutter                        0x6e840c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2966700
> 4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 5  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> io.worker.3
> 0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
> 2  Flutter                        0x45cd18 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 298424
> 3  Flutter                        0x6e840c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2966700
> 4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 5  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> io.worker.4
> 0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
> 2  Flutter                        0x45cd18 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 298424
> 3  Flutter                        0x6e840c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2966700
> 4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 5  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> io.worker.5
> 0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
> 2  Flutter                        0x45cd18 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 298424
> 3  Flutter                        0x6e840c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2966700
> 4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 5  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> io.worker.6
> 0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
> 2  Flutter                        0x45cd18 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 298424
> 3  Flutter                        0x6e840c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2966700
> 4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 5  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> dart:io EventHandler
> 0  libsystem_kernel.dylib         0x25dc kevent + 8
> 1  Flutter                        0x9a7628 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 5846728
> 2  Flutter                        0x9d511c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 6033852
> 3  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 4  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> io.worker.1
> 0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
> 2  Flutter                        0x45cd18 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 298424
> 3  Flutter                        0x6e840c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2966700
> 4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 5  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> io.worker.2
> 0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
> 2  Flutter                        0x45cd18 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 298424
> 3  Flutter                        0x6e840c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2966700
> 4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 5  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> io.worker.3
> 0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
> 2  Flutter                        0x45cd18 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 298424
> 3  Flutter                        0x6e840c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2966700
> 4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 5  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> io.worker.4
> 0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
> 2  Flutter                        0x45cd18 _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 298424
> 3  Flutter                        0x6e840c _$LT$core..core_simd..swizzle..Which$u20$as$u20$core..fmt..Debug$GT$::fmt::h8dc6fff7613f1c27 + 2966700
> 4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 5  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> Thread
> 0  libsystem_kernel.dylib         0x11ac __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0xe28 _pthread_wqthread + 364
> 2  libsystem_pthread.dylib        0xb7c start_wqthread + 8
> 
> com.google.firebase.crashlytics.MachExceptionServer
> 0  FirebaseCrashlytics            0x21794 FIRCLSProcessRecordAllThreads + 184
> 1  FirebaseCrashlytics            0x21b74 FIRCLSProcessRecordAllThreads + 1176
> 2  FirebaseCrashlytics            0x18c24 FIRCLSHandler + 48
> 3  FirebaseCrashlytics            0x1b4a8 FIRCLSMachExceptionServer + 688
> 4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 5  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> JavaScriptCore libpas scavenger
> 0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
> 2  JavaScriptCore                 0x113d84 scavenger_thread_main + 1620
> 3  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 4  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> DartWorker
> 0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x80a4 _pthread_cond_wait + 1276
> 2  Flutter                        0xa9e6c8 InternalFlutterGpuTestClass_Method + 755488
> 3  Flutter                        0xae565c InternalFlutterGpuTestClass_Method + 1046196
> 4  Flutter                        0xa9e094 InternalFlutterGpuTestClass_Method + 753900
> 5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 6  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> DartWorker
> 0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x80a4 _pthread_cond_wait + 1276
> 2  Flutter                        0xa9e6c8 InternalFlutterGpuTestClass_Method + 755488
> 3  Flutter                        0xae565c InternalFlutterGpuTestClass_Method + 1046196
> 4  Flutter                        0xa9e094 InternalFlutterGpuTestClass_Method + 753900
> 5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 6  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> DartWorker
> 0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x80a4 _pthread_cond_wait + 1276
> 2  Flutter                        0xa9e6c8 InternalFlutterGpuTestClass_Method + 755488
> 3  Flutter                        0xa35990 InternalFlutterGpuTestClass_Method + 326120
> 4  Flutter                        0xae5690 InternalFlutterGpuTestClass_Method + 1046248
> 5  Flutter                        0xa9e094 InternalFlutterGpuTestClass_Method + 753900
> 6  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 7  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> DartWorker
> 0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x80a4 _pthread_cond_wait + 1276
> 2  Flutter                        0xa9e6c8 InternalFlutterGpuTestClass_Method + 755488
> 3  Flutter                        0xae565c InternalFlutterGpuTestClass_Method + 1046196
> 4  Flutter                        0xa9e094 InternalFlutterGpuTestClass_Method + 753900
> 5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 6  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> com.apple.NSURLConnectionLoader
> 0  libsystem_kernel.dylib         0xca4 mach_msg2_trap + 8
> 1  libsystem_kernel.dylib         0x13b74 mach_msg2_internal + 80
> 2  libsystem_kernel.dylib         0x13e4c mach_msg_overwrite + 540
> 3  libsystem_kernel.dylib         0x11e8 mach_msg + 24
> 4  CoreFoundation                 0x79024 __CFRunLoopServiceMachPort + 160
> 5  CoreFoundation                 0x7a250 __CFRunLoopRun + 1208
> 6  CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
> 7  CFNetwork                      0x2586f0 _CFURLStorageSessionDisableCache + 60900
> 8  Foundation                     0x5b524 __NSThread__start__ + 716
> 9  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 10 libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> DartWorker
> 0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x80a4 _pthread_cond_wait + 1276
> 2  Flutter                        0xa9e6c8 InternalFlutterGpuTestClass_Method + 755488
> 3  Flutter                        0xae565c InternalFlutterGpuTestClass_Method + 1046196
> 4  Flutter                        0xa9e094 InternalFlutterGpuTestClass_Method + 753900
> 5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 6  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> DartWorker
> 0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x80a4 _pthread_cond_wait + 1276
> 2  Flutter                        0xa9e6c8 InternalFlutterGpuTestClass_Method + 755488
> 3  Flutter                        0xae565c InternalFlutterGpuTestClass_Method + 1046196
> 4  Flutter                        0xa9e094 InternalFlutterGpuTestClass_Method + 753900
> 5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 6  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> DartWorker
> 0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x80a4 _pthread_cond_wait + 1276
> 2  Flutter                        0xa9e6c8 InternalFlutterGpuTestClass_Method + 755488
> 3  Flutter                        0xae565c InternalFlutterGpuTestClass_Method + 1046196
> 4  Flutter                        0xa9e094 InternalFlutterGpuTestClass_Method + 753900
> 5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 6  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> DartWorker
> 0  libsystem_kernel.dylib         0x1578 __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x80a4 _pthread_cond_wait + 1276
> 2  Flutter                        0xa9e6c8 InternalFlutterGpuTestClass_Method + 755488
> 3  Flutter                        0xae565c InternalFlutterGpuTestClass_Method + 1046196
> 4  Flutter                        0xa9e094 InternalFlutterGpuTestClass_Method + 753900
> 5  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 6  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> com.apple.coremedia.rootQueue.47
> 0  libsystem_kernel.dylib         0xc38 semaphore_timedwait_trap + 8
> 1  libdispatch.dylib              0x44c4 _dispatch_sema4_timedwait + 64
> 2  libdispatch.dylib              0x4ac4 _dispatch_semaphore_wait_slow + 76
> 3  libdispatch.dylib              0x15718 _dispatch_worker_thread + 324
> 4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 5  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> com.apple.coremedia.rootQueue.47
> 0  libsystem_kernel.dylib         0xc38 semaphore_timedwait_trap + 8
> 1  libdispatch.dylib              0x44c4 _dispatch_sema4_timedwait + 64
> 2  libdispatch.dylib              0x4ac4 _dispatch_semaphore_wait_slow + 76
> 3  libdispatch.dylib              0x15718 _dispatch_worker_thread + 324
> 4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 5  libsystem_pthread.dylib        0xb88 thread_start + 8
> 
> com.apple.coremedia.rootQueue.47
> 0  libsystem_kernel.dylib         0xc38 semaphore_timedwait_trap + 8
> 1  libdispatch.dylib              0x44c4 _dispatch_sema4_timedwait + 64
> 2  libdispatch.dylib              0x4ac4 _dispatch_semaphore_wait_slow + 76
> 3  libdispatch.dylib              0x15718 _dispatch_worker_thread + 324
> 4  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
> 5  libsystem_pthread.dylib        0xb88 thread_start + 8
> ```

We would very much like to help.  0.24.0 (just released yesterday) has an updated iOS engine which fixes all crashers we know about.  It requires making a new release to use the new engine.   If that doesn't help, we're very happy to hop on a call with you an help debug!  We're also reachable live on https://discord.gg/shorebird.
