### ISSUE TITLE
fix: shorebird release use wrong flutter version even switch flutter version before

### ISSUE THREAD

**Issue by sieuhuflit** [shorebirdtech/shorebird#1693]
## Overview

Hi. My project release by shorebird cmd below.
When i use shorebird release. Somehow it's still use another flutter versions, even I'm already use shorebird flutter versions use command before.

<img width="893" alt="Screenshot 2024-02-02 at 10 22 40" src="https://github.com/shorebirdtech/shorebird/assets/7247063/fb837c13-6eea-4bc7-b78d-688a9e284296">

**Comment by eseidel** [comment]
Hmm, that looks like the tags are missing from the flutter checkout it made for 3.16.9.

**Comment by eseidel** [comment]
Yeah, looks like they were.  Try `shorebird cache clean` and try again it should work now. 🤞

**Comment by eseidel** [comment]
(The 3.16.9 tag was missing from our forked copy of Flutter, I just synced the tags and it should be fixed now after a `shorebird cache clean`.)

**Comment by eseidel** [comment]
Note to self, I thought that `cutler validate` checked for this. 🤔

**Comment by eseidel** [comment]
It does, we must just not have run cutler validate this time:
https://github.com/shorebirdtech/_build_engine/blob/main/cutler/lib/commands/validate_command.dart#L65

**Comment by eseidel** [comment]
Hmm, looks like our buildroot might be wrong too:
```
eseidel@erics-mbp cutler % dart run bin/cutler.dart validate 3.16.9
Using /Users/eseidel/Documents/GitHub as checkouts root.
✓ Checkouts updated! (11.2s)
Validating 3.16.9
✅ flutter    refs/tags/3.16.9 matches upstream 41456452f29d64e8deb623a3c927524bcf9f111b (refs/tags/3.16.9)
✅ engine     refs/tags/3.16.9 matches upstream f40e976bedff57e69e1b3d89a7c2a3c617a03dad (refs/tags/3.16.9)
❌ buildroot  flutter_release/3.16.9 does not include forkpoint f27d99b4428dea312646130d60c33a2d38fa9dc6
```

**Comment by eseidel** [comment]
Looks like we just didn't create the release branch for build_root.  Fixed with:
```
git push origin shorebird/dev:flutter_release/3.16.9
```

Dart is still "missing" because we used a merge commit, which we can fix tomorrow:
```
dart run bin/cutler.dart validate 3.16.9
Using /Users/eseidel/Documents/GitHub as checkouts root.
✓ Checkouts updated! (8.9s)
Validating 3.16.9
✅ flutter    refs/tags/3.16.9 matches upstream 41456452f29d64e8deb623a3c927524bcf9f111b (refs/tags/3.16.9)
✅ engine     refs/tags/3.16.9 matches upstream f40e976bedff57e69e1b3d89a7c2a3c617a03dad (refs/tags/3.16.9)
✅ buildroot  correctly branched
❌ dart       flutter_release/3.16.9 does not include forkpoint 3b128c5454834a1aaef37d9bb12595e7c217ab61 (3.2.6)
```

**Comment by sieuhuflit** [comment]
> shorebird cache clean

I'm already try this before, doesn't worked also

**Comment by sieuhuflit** [comment]
> Looks like we just didn't create the release branch for build_root. Fixed with:
> 
> ```
> git push origin shorebird/dev:flutter_release/3.16.9
> ```
> 
> Dart is still "missing" because we used a merge commit, which we can fix tomorrow:
> 
> ```
> dart run bin/cutler.dart validate 3.16.9
> Using /Users/eseidel/Documents/GitHub as checkouts root.
> ✓ Checkouts updated! (8.9s)
> Validating 3.16.9
> ✅ flutter    refs/tags/3.16.9 matches upstream 41456452f29d64e8deb623a3c927524bcf9f111b (refs/tags/3.16.9)
> ✅ engine     refs/tags/3.16.9 matches upstream f40e976bedff57e69e1b3d89a7c2a3c617a03dad (refs/tags/3.16.9)
> ✅ buildroot  correctly branched
> ❌ dart       flutter_release/3.16.9 does not include forkpoint 3b128c5454834a1aaef37d9bb12595e7c217ab61 (3.2.6)
> ```

Nice, thanks a lot 💯 💯 💯 will re-check it tomorrow

**Comment by eseidel** [comment]
Closing for now, please don't hesitate to reach out to us if it's not working for you or you have any other issues!

**Comment by sieuhuflit** [comment]
Hi @eseidel , just retry and it's still happen, already try clean cache also.

Do I need to wait next release included this fix or it's already fixed ?  

Thanks

**Comment by eseidel** [comment]
Hmm, I would expect it to already be fixed.  Will investigate.

**Comment by sieuhuflit** [comment]
> Hmm, I would expect it to already be fixed. Will investigate.

Thanks 💯

**Comment by bryanoltman** [comment]
It looks like the issue is that our Flutter fork doesn't contain the 3.16.9 tag (see the warning at https://github.com/shorebirdtech/flutter/tree/3.16.9). 

Edit: the reason it doesn't contain this tag is because we used a merge (instead of a rebase) when pulling in 3.16.9. Our "3.16.9" version contains all changes in upstream Flutter's 3.16.9, but our branch is missing the git tag, which is how Flutter determines its version. We've had problems with this before (see https://github.com/shorebirdtech/shorebird/issues/508)

**Comment by bryanoltman** [comment]
@sieuhuflit out of curiosity, does your pubspec.yaml specify Flutter version 3.16.9 (or version >=3.16.9) exactly?

**Comment by eseidel** [comment]
Thanks for your patience.  My fix didn't work, but Bryan has fixed it for real this time.  Release coming out shortly with a fix.

**Comment by sieuhuflit** [comment]
@bryanoltman I'm configure pubspec.yaml exactly version 3.16.9

For more context I'm using [fvm](https://github.com/leoafarias/fvm), not sure it's conflict when I'm using "shorebird flutter use" command or not

Let's me retry and will let us know if still happen 👏

**Comment by sieuhuflit** [comment]
✅  Confirm this bug solved after upgraded shorebird to 0.25.1. Thanks a lot 💯 💯 💯 

@eseidel @bryanoltman
