### ISSUE TITLE
fix: Android app fails to run (Flutter version 3.22.2)

### ISSUE THREAD

**Issue by ssorrychoi** [shorebirdtech/shorebird#2225]
After upgrading to Shorebird version 3.22.2, my Android app fails to run and is stuck on the splash screen. The app works fine when built locally in debug mode. When downloaded through internal testing, the following logs are observed after building the app locally again:

```
I/flutter (15606): [INFO:flutter/shell/common/shorebird/shorebird.cc(166)] Shorebird updater: no active patch.
I/flutter (15606): [INFO:flutter/shell/common/shorebird/shorebird.cc(170)] Starting Shorebird update
I/flutter (15606): updater::network: Sending patch check request: PatchCheckRequest { app_id: "f4876fd6-1506-408f-ac63-280186c828e3", channel: "stable", release_version: "3.20.0+730", patch_number: None, platform: "android", arch: "aarch64" }
W/FlutterJNI(15606): FlutterJNI.loadLibrary called more than once
W/FlutterJNI(15606): FlutterJNI.prefetchDefaultFontManager called more than once
W/FlutterJNI(15606): FlutterJNI.init called more than once
W/flutter (15606): updater::config: Updater already initialized, ignoring second shorebird_init call.
E/flutter (15606): updater::updater: Update failed: Update already in progress
I/flutter (15606): updater::updater: Update thread finished with status: Update had error
I/flutter (15606): updater::updater: Update thread finished with status: No update
```

Steps to Reproduce:

Upgrade to Shorebird version 3.22.2.
Build the app in debug mode and observe that it works correctly.
Download the app through internal testing.
Attempt to run the app and observe that it gets stuck on the splash screen.
Rebuild the app locally and observe the logs provided above.
Expected Behavior:
The app should transition past the splash screen and run as expected.

Actual Behavior:
The app is stuck on the splash screen after upgrading to Shorebird version 3.22.2.

Additional Information:

Platform: Android
Arch: aarch64
Flutter: 3.22.2
Shorebird: 1.1.11
App Version: 3.20.0+730
Please advise on how to resolve this issue. Thank you!

**Comment by eseidel** [comment]
Thanks for the report!  That definitely sounds unexpected.

Our server logs confirm that `{ app_id: "f4876fd6-1506-408f-ac63-280186c828e3", channel: "stable", release_version: "3.20.0+730", patch_number: None, platform: "android", arch: "aarch64" }` was built with Flutter 3.22.2 and Shorebird 1.1.11.

```
W/FlutterJNI(15606): FlutterJNI.loadLibrary called more than once
W/FlutterJNI(15606): FlutterJNI.prefetchDefaultFontManager called more than once
W/FlutterJNI(15606): FlutterJNI.init called more than once
W/flutter (15606): updater::config: Updater already initialized, ignoring second shorebird_init call.
E/flutter (15606): updater::updater: Update failed: Update already in progress
I/flutter (15606): updater::updater: Update thread finished with status: Update had error
I/flutter (15606): updater::updater: Update thread finished with status: No update
```
Looks like the Flutter engine is being initialized twice (should be fine) which happens as a result of Firebase Cloud Messaging or a few other plugins.

We used to have a hang that could occur during a second initialization, but that was fixed a month or more ago.

We'd love to work with you to figure out what's going wrong.

**Comment by ssorrychoi** [comment]
Thanks for the hint regarding the Firebase-related plugins. I'll update all of them to the latest versions and test it out!

**Comment by ssorrychoi** [comment]
Thank you for the hint regarding the Firebase-related plugins. I updated all of them to the latest versions and tried again, but I'm still encountering an issue. Below are the logs from my latest attempt:

```
✓ Built build/app/outputs/flutter-apk/app-dev-debug.apk
I/flutter (10569): [INFO:flutter/shell/common/shorebird/shorebird.cc(166)] Shorebird updater: no active patch.
I/flutter (10569): [INFO:flutter/shell/common/shorebird/shorebird.cc(170)] Starting Shorebird update
I/flutter (10569): updater::network: Sending patch check request: PatchCheckRequest { app_id: "f4876fd6-1506-408f-ac63-280186c828e3", channel: "stable", release_version: "3.20.0+731", patch_number: None, platform: "android", arch: "aarch64" }
I/flutter (10569): updater::updater: Update thread finished with status: No update
```

Could you please take another look and help me figure out what's going wrong? Thank you!

**Comment by bryanoltman** [comment]
That's the entire log output? You just see that and the app never advances past the splash screen?

**Comment by ssorrychoi** [comment]
@bryanoltman Yes,,, That's right... my application stop in splash screen in android..

**Comment by bryanoltman** [comment]
Sorry you're running into that. Would you be able to add more logs (print statements are fine) in your app's startup to get a better idea of where things are failing? Without knowing more about your app, it's tough to suggest exactly where, but ideally at least:

1. At the beginning of `main()`
2. Before `runApp` is called
3. Before and after all dependency setup (firebase, etc)

**Comment by ssorrychoi** [comment]
@bryanoltman I built my app using Shorebird on Android and uploaded it for internal testing. After downloading the app, I matched the version locally and built it. However, the only logs I see are the ones I sent. Can you please tell me how to properly log messages?

**Comment by bryanoltman** [comment]
You would create a new release (it doesn't have to be distributed to anyone, and you can delete it afterwards) with extra print/log statements, and then run `shorebird preview` to run it on a device or emulator. The goal is to gain a better understanding of where things are going wrong.

**Comment by ssorrychoi** [comment]
@bryanoltman 
I got the below log file .

✗ FormatException: Could not find End of Central Directory Record (311.6s)

2024-06-14T14:44:46.169697 
If you aren't sure why this command failed, re-run with the --verbose flag to see more information.

You can also [file an issue](https://github.com/shorebirdtech/shorebird/issues/new/choose) if you think this is a bug. Please include the following log file in your report:
/Users/djacob/Library/Application Support/shorebird/logs/1718343571043_shorebird.log

2024-06-14T14:44:46.170091 [Process.run] git symbolic-ref HEAD (in /Users/djacob/.shorebird/bin/cache)
2024-06-14T14:44:46.184276 Exited with code 0
2024-06-14T14:44:46.184438 
stdout:
refs/heads/stable

2024-06-14T14:44:46.184559 [Process.run] git rev-parse --verify HEAD (in /Users/djacob/.shorebird/bin/cache)
2024-06-14T14:44:46.191009 Exited with code 0
2024-06-14T14:44:46.191140 
stdout:
76ff1921b77fd483740de0ec92cc8afe9ac3e7d6

2024-06-14T14:44:46.191257 [Process.run] git remote prune origin (in /Users/djacob/.shorebird/bin/cache)
2024-06-14T14:44:46.883319 Exited with code 0
2024-06-14T14:44:46.883633 [Process.run] git fetch --tags (in /Users/djacob/.shorebird/bin/cache)
2024-06-14T14:44:47.517879 Exited with code 0
2024-06-14T14:44:47.518164 [Process.run] git rev-parse --verify @{upstream} (in /Users/djacob/.shorebird/bin/cache)
2024-06-14T14:44:47.524673 Exited with code 0
2024-06-14T14:44:47.524847 
stdout:
76ff1921b77fd483740de0ec92cc8afe9ac3e7d6

**Comment by bryanoltman** [comment]
This is from `shorebird preview`? Can you share the full log if so?

**Comment by ssorrychoi** [comment]
I resolved! It is not error of shorebird- Sorry.
